participation_participation:
    resource: "@ParticipationBundle/Resources/config/routing/participation.yml"
    prefix:   /participation

participation_homepage:
    path:     /
    defaults: { _controller: ParticipationBundle:Default:index }
