participation_index:
    path:     /
    defaults: { _controller: "ParticipationBundle:Participation:index" }
    methods:  GET

participation_show:
    path:     /{id}/show
    defaults: { _controller: "ParticipationBundle:Participation:show" }
    methods:  GET

participation_new:
    path:     /{id_randonnee}/new
    defaults: { _controller: "ParticipationBundle:Participation:new" }
    methods:  [GET, POST]

participation_edit:
    path:     /{id}/edit
    defaults: { _controller: "ParticipationBundle:Participation:edit" }
    methods:  [GET, POST]

participation_delete:
    path:     /{id}/delete
    defaults: { _controller: "ParticipationBundle:Participation:delete" }
